project:
  type: website
  output-dir: _site
  render:
    - "*.qmd"
    - "_posts/"
  resources:
    - files/
    - cv.html
    - resume.html

website:
  title: "juansanar"
  favicon: img/icon.png
  description: "juansanar"
  
  navbar:
    logo: img/icon.png
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Blog"
        href: blog.qmd
      - text: "CV"
        href: cv.html

format:
  html:
    theme: cosmo
    css: theme.css
    toc: true

editor: visual
